//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public int UserId { get; set; }
        public string Text { get; set; }
        public int ContentId { get; set; }
        public Nullable<int> ZhiChi { get; set; }
        public Nullable<int> FanDui { get; set; }
        public Nullable<int> LouCeng { get; set; }
        public Nullable<int> HuiFuUserId { get; set; }
        public Nullable<int> HuiFuId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Content Content { get; set; }
    }
}
