//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> See { get; set; }
        public Nullable<int> CommentNum { get; set; }
        public int LabelId { get; set; }
        public string ImagePath { get; set; }
        public int typeId { get; set; }
        public string Describe { get; set; }

        public string TypeNAme { get; set; }
        public string LabelName { get; set; }




        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Label Label { get; set; }
        public virtual Type Type { get; set; }
    }
}
