//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds105749277_dbEntities : DbContext
    {
        public qds105749277_dbEntities()
            : base("name=qds105749277_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminUser> AdminUser { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<Content> Content { get; set; }
        public DbSet<HuiFu> HuiFu { get; set; }
        public DbSet<Label> Label { get; set; }
        public DbSet<Type> Type { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<ZhiChiFanDui> ZhiChiFanDui { get; set; }
    }
}
