//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string Pwd { get; set; }
        public string UserName { get; set; }
        public string UserImg { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
